config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD

  root "welcome#home"

=======
  root 'passes#index', as: 'home'

  get 'calendar' => 'pages#calendar', as: 'calendar'
>>>>>>> 395815b473bc70fb26ece4b33bab9ffaf85a5998

<<<<<<< HEAD
  
=======
  resources :passes
>>>>>>> 395815b473bc70fb26ece4b33bab9ffaf85a5998

<<<<<<< HEAD
=======

>>>>>>> 395815b473bc70fb26ece4b33bab9ffaf85a5998
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/pass.rb
class Pass < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
<<<<<<< HEAD
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
=======
>>>>>>> 395815b473bc70fb26ece4b33bab9ffaf85a5998
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def calendar
    @title = 'Calendar'
    @content = 'This is the calendar page'
  end
end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  def index
    @passes = Pass.all
  end
  
  def show
    @pass = Pass.find(params[:id])
  end
  
  def new
  end
  
  def create
    #render plain: params[:pass].inspect
    @pass = Pass.new(pass_params)
    
    @pass.save
    redirect_to @pass
  end
  
  private def pass_params
    params.require(:pass).permit(:title, :body)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingPassPerfection</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">

      <div class="navbar-header">
        <%= link_to 'Parking Pass Perfection', home_path, class: 'navbar-brand' %>
      </div>
        
      <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav mr-auto"> 
            
            <li class="nav-item active">
                <li><%= link_to "Calendar", calendar_path, class: 'nav-link'  %></li>
            </li>
            
            <li class="nav-item active">
                <li><%= link_to "New Application", new_pass_path, class: 'nav-link' %></li>
            </li>
            
          </ul>
      </div>
  </nav> 
    
<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Parking Pass Perfection
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title Parking Pass Perfection
    
    //<=image_tag "ParkingMap1.jpg" alt="Issue loading" width="500" height="377">
    =image_tag "ParkingMap1.jpg"
    
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/pages/calendar.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/passes/index.html.erb
<h1>Parking Passes</h1>
<h2><%=image_tag "ParkingMap1.jpg" %></h2>
<% @passes.each do |pass| %>
  <h3><%= pass.title %></h3>
  <p><%= pass.body %></p>
<% end %>

app/views/passes/new.html.erb
<h1>New Pass</h1>
<%= form_for :pass, url: passes_path do |f| %>
  <p>>
    <%= f.label :name %><br>
    <%= f.text_field(:name, {:class => 'form-control'}) %>  
  </p>
  
  <p>>
    <%= f.label :licensePlate %><br>
    <%= f.text_field(:licensePlate, {:class => 'form-control'}) %>  
  </p>
  
  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/passes/show.html.erb
<h1><%= @pass.title %></h1>
<p><%= @pass.body %></p>

=image_tag "ParkingMap1.jpg"

app/views/welcome/home.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 Current Parking Slots

%table#parking
  %thead
    %tr
      %th Date
      %th Time
      %th Length of Time
      %th Class
  %tbody
    %tr
      %th 2/20
      %th 1:00-3:30PM
      %th 2Hrs 30Mins
      %th CS3300
    %tr
      %th 2/21
      %th 4:30-6:30PM
      %th 2Hrs
      %th CS3020 

<button class="button">Refresh</button>
<button class="button">Calendar</button>